# Generated by Django 4.2.1 on 2023-05-18 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medio_Pago',
            fields=[
                ('id_medio_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia usuario', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterField(
            model_name='provincia',
            name='id_provincia',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.provincia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='',
        ),
    ]
