# Generated by Django 4.2.1 on 2023-05-18 03:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0003_medio_pago_alter_provincia_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.IntegerField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('fact_id_provincia', models.IntegerField(max_length=4)),
                ('id_medio_pago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.medio_pago')),
                ('id_usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.usuario')),
            ],
        ),
    ]
