# Generated by Django 4.2.1 on 2023-05-18 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rifa',
            fields=[
                ('id_rifa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sorteo', models.CharField(max_length=100)),
                ('motivo', models.CharField(max_length=100)),
                ('organizador', models.CharField(max_length=45)),
                ('premio1', models.CharField(max_length=100)),
                ('premio2', models.CharField(max_length=100)),
                ('premio3', models.CharField(max_length=100)),
                ('cantidad_rifas', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=4)),
                ('id_organizador', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='factura',
            name='fact_id_provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.provincia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
