# Generated by Django 4.2.1 on 2023-05-18 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_rifa_alter_factura_fact_id_provincia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numeros_Rifas',
            fields=[
                ('id_numero', models.AutoField(primary_key=True, serialize=False)),
                ('id_rifa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.rifa')),
            ],
        ),
    ]
